### PR TITLE
Corrected the indexing of indexes by coordinates in CDPs

### PR DESCRIPTION
**Pull request by lepeuvedic-natixar**
As per the API Specification-Data Endpoint Rev.D the compressed data points coordinates are positions in the arrays containing the hierarchical indexes. The "id" field is only used in conjunction with the "parent" field, to define the hierarchies themselves.

### CODE REVIEW

**Comment by ChrisNatixar** [comment]
The calculateTotalAmount and getTimeDeltaForSlot have been changed, there is a very similar total calculation in emissionsGroupByTime which also uses getTimeDeltaForSlot. This calculation should be checked to make sure it hasn't been altered due to these changes.

**Review by ChrisNatixar — DISMISSED** [review]

**Comment by lepeuvedic-natixar** [comment]
> The calculateTotalAmount and getTimeDeltaForSlot have been changed, there is a very similar total calculation in emissionsGroupByTime which also uses getTimeDeltaForSlot. This calculation should be checked to make sure it hasn't been altered due to these changes.

I am checking

**Comment by lepeuvedic-natixar** [comment]
I did not change results nor semantics for ``getTimeDeltaForSlot`` and ``getTimeOffsetForSlot``. Other uses shouldn't be affected, but the calculations may be faulty elsewhere, like they were in totalAmount before my change. I had always wanted to check in the bar chart data was in fact consistent with the donut.

**Comment by lepeuvedic-natixar** [comment]
### emissionsGroupByTime in emissionTransformers.ts
It would sure need to be modified to show break down by scope instead of era, but I'll do that later in a separate change. I'll keep the era breakdown, unfortunately in some taxonomies, era is undefined for some categories, and when this happens, it necessarily propagates to the group. The group has a defined era only when all the grouped categories have the same era, and that's rather infrequent.

I'll just check the calculations to make sure they're correct, or update them, so that they add up, whatever the break down is.

**Review by lepeuvedic — APPROVED** [review]
Leave branch open to check for other incorrect emissions calculations, especially in emissionsGroupByTime. But since the server has been updated already, it's urgent to let other branches merge those changes from main.

**Pull request merged**
