### PR TITLE
64 Remove all fake data from all pages  

### PR DESCRIPTION
**Pull request by Math712**

### CODE REVIEW

**Comment by Math712** [comment]
With my investigation i find out just 2 spot diplayed some fake data

**Review by ChrisNatixar — COMMENTED** [review]
This fix adds text that says Fake data Displayed on the relevant pages. Is that the intended fix or should correct data be added?

**Comment by Math712** [comment]
Linked to #13, #14, #15, #16.
May be merge informations into this thread and close theses old issues.

**Comment by ChrisNatixar** [comment]
Closing PR as changes have been addressed via other PRs

**Pull request closed without merging**
