### PR TITLE
add filters on smaller screens

### PR DESCRIPTION
**Pull request by astowny**
I added the filters in a button that open a dialog modal to use the same filters that are on larger screens.
I added also the generate report button and the button to select the different protocols, as I didn't see them on smaller screens.

### CODE REVIEW

**Comment by lepeuvedic-natixar** [comment]
Filters modal must be flex flow
Almost good. Change style attributes to ensure the modal is flex flow in all its box elements. The current version always tries to layout the filters side-by-side even when there is not enough space to do so.

**Review by lepeuvedic-natixar — CHANGES_REQUESTED** [review]
Please change style to make sure that all the filters can line up vertically when the screen is not very wide, like on a mobile phone.

**Comment by astowny** [comment]
@lepeuvedic-natixar @lepeuvedic it should be fine now

**Review by lepeuvedic-natixar — CHANGES_REQUESTED** [review]
The new modal works fine on mobiles and narrow screens.
I'll merge into dev, but the branch must be brought up-to-date with respect to main before I can close the PR.

**Review by lepeuvedic-natixar — APPROVED** [review]
Works ok now.

**Pull request merged**
